### ISSUE TITLE
rename project to ng-redux or diff name as ng2 no longer applies

### ISSUE THREAD

**Issue by born2net** [angular-redux/store#288]
rename project to ng-redux or diff name as ng(2) no longer applies...
be sure to set a GitHub redirect...
regards

Sean

**Comment by SethDavenport** [comment]
Yeah there's already a project called ng-redux.  Its for AngularJS (1.x)... so we'll need to agree on a better name.  Something's in the works.

**Comment by SethDavenport** [comment]
Current proposal is at #304

**Comment by SethDavenport** [comment]
Now that Angular 4 is in beta, we need to update our package's naming since ng2-redux doesn't make a lot of sense any more.

After conferring with my colleagues we're thinking of also taking the opportunity to move to scoped pages under our github org (`@angular-redux`).

The current idea is as follows:

* ng2-redux -> `@angular-redux/store` [UPDATED, was `core` before]
* ng2-redux-router -> `@angular-redux/router`
* ng2-redux-form -> `@angular-redux/form`

... with potentially others down the line.

This PR starts the process of updating ng2-redux to `@angular-redux/core`.

@dagstuan @clbond if you're cool with this idea, I'll make some PRs for ng2-redux-router, ng2-reux-form, and also work with you to get them published on npm under the new scope.

* [x] get router up and running with latest deps (angular-redux/router#1)
* [x] get form up and running with latest deps
* [x] extract store, form, router examples into an example repo (see [angular-redux/example-app](https://github.com/angular-redux/example-app))
* [x] harmonize ngModule naming across form/store/router
* [ ] harmonize package versions
* [ ] simplify existing in-repo examples to be simple test benches on local code
* [ ] make sure the docs are up to date
* [ ] make sure the code examples are up to date
* [ ] rename GH repos
* [ ] deprecate old npm packages
* [ ] update gitter room

**Comment by SethDavenport** [comment]
We are now live with the new package naming strategy! See the changelog for details: https://github.com/angular-redux/store/blob/master/CHANGELOG.md#600---the-big-rename
