### ISSUE TITLE
Write better 'getting started' guide

### ISSUE THREAD

**Issue by SethDavenport** [angular-redux/store#314]
I'm getting feedback that our docs are a bit hard for newcomers to grok. I'd like to improve this.

* Start a very quick summary & some links to reducer basics.
* Then show hooking up the store
* Then show an `@select`
* Then show something with `store.select`
* Then show routing
* Then show forms
* Then show an epic.

**Comment by dguisinger** [comment]
Hey Seth,
I have to say, everything I do seems like its probably not the best way.

Typical example:
Many of the components of my app grab data from several separate areas of the state.

1) a drop down list from state.typea.entities.filter(filter to route parameter)
2) a drop down list from state.typeb.entities.filter(filter where typea_id = id from selection in dropdown #1)
3) UI state for the particular page, which i store in a KV map in state.uisettings.entities['uicomponent keyname']

So why this gets ugly quickly.  I start throwing a bunch of properties onto the component.
typeAs$ and typeBs$ are Observable<typeX[]>
I then store the selected item as separate typeA and typeB objects on the component, so I can access them without dealing with the observables

I try to store IDs of selected items into the settings keyvalue store instead of the physical properties, but it then becomes a large chain of selects and observers and just seems to be a convoluted mess.

So if you can show how to do a more advanced page that uses multiple sections of data from the state that chain together in the UI, that would be great.

**Comment by SethDavenport** [comment]
Can you provide an example of the messy areas? I can try and make some suggestions based on that.
