### ISSUE TITLE
Redux batch middleware not working correctly

### ISSUE THREAD

**Issue by olaf89** [angular-redux/store#372]
Hey, i was trying to use @manaflair/redux-batch enhancer with store, and its not working as expected.

The problem is that store selectors are called every actions, for example if 5 actions are batched selectors are called 5 times. Its only happening when using select, when using subscribe exposed by store it works fine. Redux allows to manage when listeners are called, but using select takes away this flexibility, which is a problem.

Since in application im working on it was causing performance issue we had to implement a way around this, we really did not want to give up select since its used all over, we modified it a little:

const overrideSelect = (ngRedux: NgRedux<AppState>) => {
    const result$ = new BehaviorSubject(undefined);
    ngRedux.subscribe(() => result$.next(undefined));
    ngRedux['_store$'] = ngRedux['_store$'].sample(result$)
};

this way the subscribe dictates when selectors are called.

**Comment by SethDavenport** [comment]
So each call to `select` generates a new subscription? When to those get cleaned up?

**Comment by SethDavenport** [comment]
I'd have to dig into the implementation of redux-batch to see if it handles using redux as an observable or if it just patches the regular subscription mechanism.

One alternative in your case might be to call `select` with one of RxJS's buffering operators?

**Comment by olaf89** [comment]
about solution i shared its done only on bootstrap.
Middleware i reported not working correctly is using subscription mechanism. Lets say you want to dispatch 5 actions, you would like your selectors to be called only once, after final state change. This is build in into redux-batch middleware, there are many implementation of that so ill share the example one : https://github.com/manaflair/redux-batch

**Comment by SethDavenport** [comment]
OK yeah I reproduced the issue here https://github.com/SethDavenport/redux-batch-example and finally found time to dig into it a little more.

The problem is that redux-batch works by overriding the way redux manages `subscribe` and listeners. In particular, redux-batch appears to keep its own list of listeners from its own version of `subscribe`. However, patching store.subscribe is in my opinion insufficient as an abstraction, because since Redux 3.5 there's an observable-based mechanism than needs to be patched as well.

Your solution is interesting; however I don't think angular-redux is the right place for this since `subscribe(() => result$.next())` effectively duplicates a mechanism already provided internally to redux.

Let me see if I can come up with a PR to redux-batch.

**Comment by SethDavenport** [comment]
On second though - redux `Store.observable()` isn't a fully-fledged RxJS observable, which is resulting in some interop problems.  I can bake the non-sample portion of your solution into how we observablify the store - see #397.

@olaf89 give `@angular-redux/store@6.3.0-alpha.0` and let me know.

**Comment by olaf89** [comment]
I confirm it is solving the problem. Thanks!
