### ISSUE TITLE
Custom Selectors

### ISSUE THREAD

**Issue by pfrendo** [angular-redux/store#441]
Hi Guys, 

Is there any way where you can create custom selectors (ngrx style)? 

Something like the following? Basically all I require is access to the state.

```
import { Injectable } from "@angular/core";  
import { Observable } from "rxjs/Observable";

import { AlbumState, Album } from "./album.model";

@Injectable()
export class albumSelector {

    getAllAlbums() {
        return ($state: AlbumState): Album[] =>
            $state.albums;
    }
}
```

**Comment by SethDavenport** [comment]
Yes, there are several ways to do this.

**Your way, with [NgRedux.select](https://angular-redux.github.io/store/classes/ngredux.html#select) and a [FunctionSelector](https://angular-redux.github.io/store/globals.html#functionselector)**

You can pass your function above into `ngRedux.select`:

```typescript
import { AlbumSelector } from './album-selector';

@Component({ /* etc. ... */ })
class MyComponent {
  readonly albums$: Observable<Album[]>;

  constructor(store: NgRedux<IAppState>, albumSelector: AlbumSelector) {
    this.albums$ = store.select(AlbumSelector.getAllAlbums);
  }
}
```

**Your way, with NgRedux.select and a FunctionSelector that has access to AlbumSelector.this:**

If for some reason your `AlbumSelector.getAllAlbums()` needs to depend on another injectable service, you could define it using a member arrow function to get the right value of `this` when you call `.select` (although I don't really recommend this pattern since `FunctionSelectors` should really be pure functions):

_album-selector.ts:_

```
import { Injectable } from "@angular/core";  
import { Observable } from "rxjs/Observable";

import { AlbumState, Album } from "./album.model";

@Injectable()
export class albumSelector {
    constructor(private someOtherService: SomeOtherService) {}

    // Define method as an arrow function to bind `this` properly
    getAllAlbums = () => {
        return ($state: AlbumState): Album[] =>
          this.someTransform.doStuff($state.albums);  
    }
}
```

Component as before.

**Using a pure FunctionSelector and the [@select decorator](https://angular-redux.github.io/store/globals.html#select):**

The `@select` decorator also supports FunctionSelectors, although not DI since it runs during class definition time. However since selectors should be pure functions this is in some ways a good limitation:

_album-selector.ts:_

```typescript
export function getAllAlbums($state => $state.albums)
```

_my-component.ts:_
```typescript
import { getAllAlbums } from './album-selector';

@Component({ /* etc. ... */ })
class MyComponent {
  // Note that due to limitations in Angular's AoT compiler, we need to use an exported
  // named function in the decorator.  @select($state => state.albums) only works in
  // JiT mode. But an exported FunctionSelector is better for testability anyway.
  @select(getAllAlbums) readonly albums$: Observable<Album[]>;
}
```

**Special Case with a [Transformer](https://angular-redux.github.io/store/globals.html#transformer) and the [@select$](https://angular-redux.github.io/store/globals.html#select_) decorator:**

Finally, in the special case where your custom selector amounts to an `Observable` operator chain, you can use a `Transformer` with the `@select$` shorthand:

```typescript
export const extractAlbumTitles = (albums$: Observable<Album[]>): Observable<string> =>
  albums$
    .map(uniq)
    .pluck(title);

@Component({ /* etc. ... */ })
class MyComponent {
  @select(getAllAlbums)
  readonly albums$: Observable<Album[]>;

  @select$('albums', extractAlbumTitles)
  readonly albumTitles$: Observable<string>;
}
```

**Comment by e-schultz** [comment]
There is nothing stopping you from doing this.

One approach that I have been experimenting with a bit, is having a service that bundles up various selectors/action creators/etc - and injecting that into your components instead of having them rely on `@select` or `ngRedux` directly. 

Some rough notes on this style can be found [here](https://hackmd.io/s/ryiVSuFmZ) - notes/guide was WIP, but can expand on that here if you want. Hopefully between seths response and this, it points you in the right direction.

**Comment by pfrendo** [comment]
Thank for the reply! I tried the @select which I like but I would only use for a certain set of cases, I just needed the other option which @SethDavenport provided me with, thanks 👍
