### ISSUE TITLE
@actionService parameter decorator

### ISSUE THREAD

**Issue by kosz** [angular-redux/store#98]
**As a developer** using the ng2-redux library
**I want to** be able to decorate a constructor parameter
**So that I can** quickly,  with minimum code footprint attach dispatched actions from the ActionCreatorService instance contained in that  parameter to my Angular 2 Component/Injectable class

Subtasks here would be:
- assess cross requirements with the Injectable Action Services pattern
- write specs
- write example usage in example app
- implement the decorator
- update docs

**Comment by e-schultz** [comment]
@kosz what would the usage of this look like?

is the idea that if you had `someService.action()` that instead of doing `.dispatch(someService.action())` - the decorated one would take care of that for you, so `someService.action()` would dispatch itself?

**Comment by kosz** [comment]
yea basically if I remember the thought correctly, it was supposed to be the equivalent of @dispatchAll for @Injectable Services which contain Action creators. 

We would need to decorators to achieve this: 


```ts
@Injectable
export default class MyActionCreatorService {
   private someInnerLogicFunction = () => {

   }

   @action aPublicActionCreator = () => {

   }
}
```

then the component would: 

```ts
export default MyComponent {
   constructor(@actionService myActionCreatorService) {}
}
```

so at this point I can in my template do : 
```html
  <button (click)="aPublicActionCreator()">Ok</button>
```

while : 
```html
  <button (click)="someInnerLogicFunction()">Ok</button>
```
wouldn't be available because the @actionService decorator would ensure that only @action flagged functions get mixedin/dispatched.

**Comment by e-schultz** [comment]
Question about this one, and might close this for the time being. 

* if we were to give an `@action` or `@dispatch` attribute to a method, would the expected behaviour be.

a) The action gets dispatched - but the POJO still gets returned
b) The action gets dispatched, and the result of the dispatch (void) gets returned.

```ts
export class SomeClass {
   @action doThing(id, text) { 
     return {
       type: 'SOME_ACTION',
       payload: { id, text }
     }
   } 
  }
```

* someClass.doThing() - would this return the POJO, or a result of ngRedux.dispatch({POJO});

Would make sense for it to return the POJO object - and keep in with the idea of these being simple action creators, unit testing on them then gets to be a bit easier as we don't need to spy on what ngRedux.dispatch was called with - can just check the returned object. 

although as I adopt redux-observable more and more, I'm finding that I have a preference for my action creators to going back to simple functions that return POJO's and not needing to create them as injectable calsses that use ngRedux.dispatch internally.

**Comment by SethDavenport** [comment]
See discussion on #385

**Comment by SethDavenport** [comment]
We released a `@dispatch` method decorator a while ago - I think that covers the use case here.
